---
name: ci
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
      - "dev/**"
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    name: build & upload firmware
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: update and install apt dependancies
        run: |
          sudo apt update -y
          sudo apt install -y gcc-avr
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.22.x'
      - name: build
        run: |
          mkdir $GITHUB_WORKSPACE/build
          cd build
          cmake ..
          make -j`nproc`
      - name: binary object dump
        working-directory: build 
        run: make objdump
      - name: archive binary 
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          # relative to $GITHUB_WORKSPACE 
          path: build/*.elf
          retention-days: 5